---
- name: Copy the content using python
  hosts: webservers
  tasks:
    - name: update the content
      ansible.builtin.copy:
        content: "Sun set down in east"
        dest: /etc/motd.d/banner
