---
- name: creating variables
  hosts: all
  tasks:
    - name: create directory
      ansible.builtin.file:
         path: "{{DIRECTORY}}"
         state: directory
    - name: create file
      ansible.builtin.file:
         path: "{{FILE}}"  
         state: touch
    - name: copying a content
      ansible.builtin.copy:
         content: "{{CONTENT}}"  
         dest: "{{DIRECTORY}}/{{FILE}}"   
         
